#!/bin/bash -eu

cd $(dirname $0)/..

IMAGE=service-template
APP_VERSION=0.0.1

echo "--- Building Jar"
auto/build-jar

echo "--- Building docker image"
docker build -t "${IMAGE}:${APP_VERSION}" -f docker/Dockerfile .
